# This is a basic workflow to help you get started with Actions

name: CI

env:
  VERSION: ${{ github.ref_name }}
  BUILD:
  UPDATE:
  RELEASE:

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
    - '*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install prerequies
        run: |
          sudo apt-get update
          sudo apt install libguestfs-tools binfmt-support coreutils cryptsetup-bin e2fsprogs lvm2 mount parted qemu-user-static qemu-utils wget lsb-release ucommon-utils
      # Runs a set of commands using the runners shell
      - name: Download base image from Oracle Repository
        run: |
         sudo wget https://yum.oracle.com/templates/OracleLinux/OL${{ env.VERSION }}/u${{ env.UPDATE }}/x86_64/OL${{ env.VERSION }}U${{ env.UPDATE }}_x86_64-kvm-b${{ env.BUILD }}.qcow
      - name: Making some changes on base image
        run: |
         qemu-img convert -f qcow2 -O raw amzn2-kvm-${{ env.VERSION }}-x86_64.xfs.gpt.qcow2 amzn2-kvm.raw
         sudo mount -o loop,offset=2097152 amzn2-kvm.raw /mnt
         sudo cp config/cloud.cfg /mnt/etc/cloud/cloud.cfg
         sudo umount /mnt
         sudo rm amzn2-kvm-${{ env.VERSION }}-x86_64.xfs.gpt.qcow2
         sudo qemu-img convert -f raw -O qcow2 amzn2-kvm.raw amzn2-kvm-${{ env.VERSION }}-x86_64.xfs.gpt-tmp.qcow2
      - name: Sparsify image
        run: |
         sudo virt-sparsify --convert qcow2 --compress amzn2-kvm-${{ env.VERSION }}-x86_64.xfs.gpt-tmp.qcow2 amzn2-kvm-${{ env.VERSION }}-x86_64.xfs.gpt.qcow2
         sudo md5sum amzn2-kvm-${{ env.VERSION }}-x86_64.xfs.gpt.qcow2 > md5.txt
